# Generated by Django 2.2.4 on 2019-08-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='datebirth',
            field=models.DateTimeField(default=0, verbose_name='datebirth'),
        ),
    ]
