# Generated by Django 2.2.4 on 2019-08-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_datebirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datebirth',
            field=models.DateTimeField(default='', verbose_name='datebirth'),
        ),
    ]
