# Generated by Django 2.2.4 on 2019-08-26 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190825_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='datebirth',
        ),
        migrations.AddField(
            model_name='user',
            name='d_nasc',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
        ),
    ]
