# Generated by Django 2.2.4 on 2019-08-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190825_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='d_nasc',
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dtNascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
